CREATE TABLE urls
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    short_code   VARCHAR(255),
    original_url VARCHAR(255),
    click_count  INTEGER,
    user_id      BIGINT,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_urls PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255),
    password_hash VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE urls
    ADD CONSTRAINT FK_URLS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);